# Generated by Django 3.1.7 on 2021-04-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_auto_20210403_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrating',
            name='already_rated',
            field=models.BooleanField(default=False),
        ),
    ]
