# Generated by Django 3.1.7 on 2021-04-04 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_mealrating_already_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrating',
            name='already_rated',
        ),
    ]
