# Generated by Django 3.1.7 on 2021-03-31 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0036_delete_food'),
        ('enrolments', '0011_auto_20210329_0219'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='stores.store')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='enrolments.extendeduser')),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enrolment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='enrolments.enrolment')),
            ],
        ),
        migrations.CreateModel(
            name='FighterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='delivery_fighters.deliveryfighter')),
                ('requester', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store_request', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='store_request', to='stores.store')),
            ],
        ),
    ]
