# Generated by Django 3.1.7 on 2021-03-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_fighters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighterrequest',
            name='fighter',
        ),
        migrations.RemoveField(
            model_name='fighterrequest',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='fighterrequest',
            name='store_request',
        ),
        migrations.DeleteModel(
            name='DeliveryFighter',
        ),
        migrations.DeleteModel(
            name='FighterRequest',
        ),
    ]
