# Generated by Django 3.1.7 on 2021-03-30 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0011_auto_20210329_0219'),
        ('delivery_fighters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryfighter',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='deliveryfighter',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='deliveryfighter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='deliveryfighter',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='deliveryfighter',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='deliveryfighter',
            name='preferred_location',
        ),
        migrations.AlterField(
            model_name='deliveryfighter',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='enrolments.extendeduser'),
        ),
    ]
