# Generated by Django 3.1.7 on 2021-03-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0036_delete_food'),
        ('delivery_fighters', '0002_auto_20210331_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryfighter',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
