# Generated by Django 3.1.7 on 2021-03-31 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrolments', '0011_auto_20210329_0219'),
        ('delivery_fighters', '0003_deliveryfighter_fighterrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meals',
            new_name='Meal',
        ),
    ]
