# Generated by Django 3.1.7 on 2021-03-30 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0036_delete_food'),
        ('delivery_fighters', '0003_deliveryfighter_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryfighter',
            name='store_requests',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_request', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='deliveryfighter',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='stores.store'),
        ),
    ]
