# Generated by Django 3.1.7 on 2021-03-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_fighters', '0004_auto_20210331_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='code',
            field=models.CharField(default=1058, max_length=4, unique=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
