# Generated by Django 3.1.7 on 2021-03-31 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_fighters', '0004_auto_20210331_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryfighter',
            name='store_requests',
        ),
    ]
