# Generated by Django 3.1.7 on 2021-03-31 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0036_delete_food'),
        ('delivery_fighters', '0005_remove_deliveryfighter_store_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='FighterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='delivery_fighters.deliveryfighter')),
                ('request', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
