# Generated by Django 3.1.7 on 2021-03-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_fighters', '0005_auto_20210401_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='code',
            field=models.CharField(default=3231, max_length=4),
        ),
    ]
