# Generated by Django 3.1.7 on 2021-03-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_fighters', '0006_auto_20210401_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
