# Generated by Django 3.1.7 on 2021-03-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_fighters', '0006_fighterrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighterrequest',
            old_name='request',
            new_name='store_request',
        ),
    ]
