# Generated by Django 3.1.7 on 2021-04-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_fighters', '0007_auto_20210401_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
