# Generated by Django 3.1.7 on 2021-03-31 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0036_delete_food'),
        ('delivery_fighters', '0007_auto_20210331_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighterrequest',
            name='requester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fighterrequest',
            name='store_request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='store_request', to='stores.store'),
        ),
    ]
