# Generated by Django 3.1.7 on 2021-03-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0003_auto_20210328_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
