# Generated by Django 3.1.7 on 2021-03-28 15:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0035_auto_20210326_0227'),
        ('enrolments', '0004_extendeduser_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(100)])),
                ('special_note', models.CharField(default='Call my brother if I dont pick up', max_length=500)),
                ('pause', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stores.plan')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='enrolments.extendeduser')),
            ],
        ),
    ]
