# Generated by Django 3.1.7 on 2021-03-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0006_auto_20210329_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='duration',
        ),
    ]
