# Generated by Django 3.1.7 on 2021-03-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0007_remove_enrolment_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolment',
            old_name='pause',
            new_name='send',
        ),
    ]
