# Generated by Django 3.1.7 on 2021-03-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0008_auto_20210329_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='send',
            field=models.BooleanField(default=True),
        ),
    ]
