# Generated by Django 3.1.7 on 2021-03-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0009_auto_20210329_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='send',
        ),
        migrations.AddField(
            model_name='enrolment',
            name='daily_meal_count',
            field=models.IntegerField(default=2),
        ),
    ]
