# Generated by Django 3.1.7 on 2021-04-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0011_auto_20210329_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100),
        ),
    ]
