# Generated by Django 3.1.7 on 2021-04-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0012_extendeduser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='age',
            field=models.IntegerField(default=25),
        ),
    ]
