# Generated by Django 2.2 on 2021-03-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_ratings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
