# Generated by Django 2.2 on 2021-03-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_delete_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(default='01719500600', max_length=12),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, default='This is the description area...', null=True),
        ),
    ]
