# Generated by Django 2.2 on 2021-03-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20210314_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.CharField(blank=True, default='This is the description area...', max_length=1000, null=True),
        ),
    ]
