# Generated by Django 2.2 on 2021-03-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20210314_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Fish', 'Fish'), ('Rice', 'Rice'), ('Dal', 'Dal'), ('Meet', 'Meet'), ('Vegetable', 'Vegetable'), ('Desert', 'Desert'), ('Special', 'Special')], max_length=1000)),
                ('name', models.CharField(default='Detail Food name', max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('calorie', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='display_picture',
            field=models.ImageField(default='store.gif', upload_to='pics/stores'),
        ),
    ]
