# Generated by Django 2.2 on 2021-03-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20210314_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='food_1', to='stores.FoodDetail')),
                ('food_2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_2', to='stores.FoodDetail')),
                ('food_3', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_3', to='stores.FoodDetail')),
                ('food_4', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_4', to='stores.FoodDetail')),
                ('food_5', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_5', to='stores.FoodDetail')),
                ('food_6', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_6', to='stores.FoodDetail')),
                ('food_7', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_7', to='stores.FoodDetail')),
                ('food_8', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_8', to='stores.FoodDetail')),
            ],
        ),
    ]
