# Generated by Django 2.2 on 2021-03-14 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday_day', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friday_day', to='stores.Food')),
                ('friday_night', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friday_night', to='stores.Food')),
                ('monday_day', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='monday_day', to='stores.Food')),
                ('monday_night', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='monday_night', to='stores.Food')),
                ('saturday_day', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_day', to='stores.Food')),
                ('saturday_night', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_night', to='stores.Food')),
                ('sunday_day', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_day', to='stores.Food')),
                ('sunday_night', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_night', to='stores.Food')),
                ('thursday_day', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_day', to='stores.Food')),
                ('thursday_night', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_night', to='stores.Food')),
                ('tuesday_day', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_day', to='stores.Food')),
                ('tuesday_night', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_night', to='stores.Food')),
                ('wednesday_day', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_day', to='stores.Food')),
                ('wednesday_night', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_night', to='stores.Food')),
            ],
        ),
    ]
