# Generated by Django 2.2 on 2021-03-14 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('capacity', models.IntegerField(default=10)),
                ('total_calorie', models.FloatField(default=0.0)),
                ('photo_1', models.ImageField(default='plan.png', upload_to='pics/plans')),
                ('photo_2', models.ImageField(default='plan.png', upload_to='pics/plans')),
                ('photo_3', models.ImageField(default='plan.png', upload_to='pics/plans')),
                ('photo_4', models.ImageField(default='plan.png', upload_to='pics/plans')),
                ('photo_5', models.ImageField(default='plan.png', upload_to='pics/plans')),
                ('store', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stores.Store')),
                ('weekly', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stores.Week')),
            ],
        ),
    ]
