# Generated by Django 2.2 on 2021-03-19 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_5',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_6',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_7',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_8',
        ),
        migrations.RemoveField(
            model_name='week',
            name='friday_day',
        ),
        migrations.RemoveField(
            model_name='week',
            name='friday_night',
        ),
        migrations.RemoveField(
            model_name='week',
            name='monday_day',
        ),
        migrations.RemoveField(
            model_name='week',
            name='monday_night',
        ),
        migrations.RemoveField(
            model_name='week',
            name='saturday_day',
        ),
        migrations.RemoveField(
            model_name='week',
            name='saturday_night',
        ),
        migrations.RemoveField(
            model_name='week',
            name='sunday_day',
        ),
        migrations.RemoveField(
            model_name='week',
            name='sunday_night',
        ),
        migrations.RemoveField(
            model_name='week',
            name='thursday_day',
        ),
        migrations.RemoveField(
            model_name='week',
            name='thursday_night',
        ),
        migrations.RemoveField(
            model_name='week',
            name='tuesday_day',
        ),
        migrations.RemoveField(
            model_name='week',
            name='tuesday_night',
        ),
        migrations.RemoveField(
            model_name='week',
            name='wednesday_day',
        ),
        migrations.RemoveField(
            model_name='week',
            name='wednesday_night',
        ),
        migrations.AddField(
            model_name='plan',
            name='category',
            field=models.CharField(choices=[('Homemade', 'Homemade'), ('Professional', 'Professional')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_day_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_day_1', to='stores.Food'),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_day_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_day_2', to='stores.Food'),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_day_3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_day_3', to='stores.Food'),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_day_4',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_day_4', to='stores.Food'),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_night_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_night_1', to='stores.Food'),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_night_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_night_2', to='stores.Food'),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_night_3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_night_3', to='stores.Food'),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_night_4',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_night_4', to='stores.Food'),
        ),
    ]
