# Generated by Django 2.2 on 2021-03-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_auto_20210320_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddetail',
            name='amount',
            field=models.CharField(default='100 g', max_length=100),
        ),
        migrations.AlterField(
            model_name='fooddetail',
            name='calorie',
            field=models.FloatField(default=0.0),
        ),
    ]
