# Generated by Django 2.2 on 2021-03-23 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_auto_20210320_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='weekly',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.Week'),
        ),
    ]
