# Generated by Django 2.2 on 2021-03-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_auto_20210323_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='total_calorie',
            new_name='total_estimated_calorie',
        ),
    ]
