# Generated by Django 2.2 on 2021-03-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_plan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='photo_5',
        ),
    ]
