# Generated by Django 2.2 on 2021-03-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_auto_20210323_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
