# Generated by Django 2.2 on 2021-03-24 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_auto_20210324_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='saturday_day_1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='saturday_day_2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='saturday_day_3',
        ),
        migrations.RemoveField(
            model_name='week',
            name='saturday_day_4',
        ),
        migrations.RemoveField(
            model_name='week',
            name='saturday_night_1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='saturday_night_2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='saturday_night_3',
        ),
        migrations.RemoveField(
            model_name='week',
            name='saturday_night_4',
        ),
        migrations.AddField(
            model_name='week',
            name='friday_day_food_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friday_day_1', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='friday_day_food_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday_day_2', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='friday_day_food_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday_day_3', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='friday_day_food_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday_day_4', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='friday_night_food_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friday_night_1', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='friday_night_food_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday_night_2', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='friday_night_food_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday_night_3', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='friday_night_food_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday_night_4', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='monday_day_food_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='monday_day_1', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='monday_day_food_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday_day_2', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='monday_day_food_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday_day_3', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='monday_day_food_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday_day_4', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='monday_night_food_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='monday_night_1', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='monday_night_food_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday_night_2', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='monday_night_food_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday_night_3', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='monday_night_food_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday_night_4', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_day_food_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_day_1', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_day_food_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_day_2', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_day_food_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_day_3', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_day_food_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_day_4', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_night_food_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_night_1', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_night_food_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_night_2', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_night_food_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_night_3', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday_night_food_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_night_4', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='sunday_day_food_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_day_1', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='sunday_day_food_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_day_2', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='sunday_day_food_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_day_3', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='sunday_day_food_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_day_4', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='sunday_night_food_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_night_1', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='sunday_night_food_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_night_2', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='sunday_night_food_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_night_3', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='sunday_night_food_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_night_4', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='thursday_day_food_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_day_1', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='thursday_day_food_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_day_2', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='thursday_day_food_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_day_3', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='thursday_day_food_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_day_4', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='thursday_night_food_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_night_1', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='thursday_night_food_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_night_2', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='thursday_night_food_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_night_3', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='thursday_night_food_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_night_4', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='tuesday_day_food_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_day_1', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='tuesday_day_food_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_day_2', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='tuesday_day_food_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_day_3', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='tuesday_day_food_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_day_4', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='tuesday_night_food_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_night_1', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='tuesday_night_food_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_night_2', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='tuesday_night_food_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_night_3', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='tuesday_night_food_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_night_4', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='wednesday_day_food_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_day_1', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='wednesday_day_food_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_day_2', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='wednesday_day_food_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_day_3', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='wednesday_day_food_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_day_4', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='wednesday_night_food_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_night_1', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='wednesday_night_food_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_night_2', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='wednesday_night_food_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_night_3', to='stores.FoodDetail'),
        ),
        migrations.AddField(
            model_name='week',
            name='wednesday_night_food_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_night_4', to='stores.FoodDetail'),
        ),
    ]
