# Generated by Django 2.2 on 2021-03-25 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_auto_20210324_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='weekly',
        ),
        migrations.AddField(
            model_name='week',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stores.Plan'),
        ),
    ]
