# Generated by Django 2.2 on 2021-03-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0027_auto_20210325_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailfood',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.Store'),
            preserve_default=False,
        ),
    ]
