# Generated by Django 2.2 on 2021-03-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0028_auto_20210325_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailFood',
        ),
    ]
