# Generated by Django 2.2 on 2021-03-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0030_fooddetail_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddetail',
            name='store',
        ),
    ]
