# Generated by Django 2.2 on 2021-03-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0031_remove_fooddetail_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddetail',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stores.Store'),
        ),
    ]
