# Generated by Django 2.2 on 2021-03-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0032_fooddetail_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='visibility',
            field=models.BooleanField(default=None),
        ),
    ]
