# Generated by Django 2.2 on 2021-03-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0034_auto_20210326_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
