# Generated by Django 3.1.7 on 2021-03-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0035_auto_20210326_0227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
